# -------- Gradle Performance --------
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# Fast filesystem watching (important for --continuous)
org.gradle.vfs.watch=true


# -------- Build Cache --------
# Enables local build cache reuse between modules
org.gradle.caching=true

# -------- JVM Settings --------
# Reasonable memory for container builds
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8


# -------- Kotlin DSL Optimization --------
org.gradle.kotlin.dsl.precompiled.accessors=true


# -------- Console / Logging --------
org.gradle.console=rich
org.gradle.warning.mode=all


# -------- Continuous Build Friendliness --------
org.gradle.unsafe.watch-fs=true