# -------- Gradle Performance --------
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configureondemand=true


# -------- Build Cache --------
# Enables local build cache reuse
org.gradle.caching=true

# -------- JVM Settings --------
# Reasonable memory for container builds
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8


# -------- Kotlin DSL Optimization --------
org.gradle.kotlin.dsl.precompiled.accessors=true


# -------- Console / Logging --------
org.gradle.console=rich
org.gradle.warning.mode=all
