include:
  - infra.kafka.yml

services:
  # anchor, x- means extension field so this service gets ignored by execution
  x-java-service: &java-service
    build:
      context: ../..
      dockerfile: ../dev/java-service.Dockerfile

    volumes:
      - .:/workspace
      - gradle-cache:/root/.gradle

    command: ./gradlew bootRun --continuous

  idp-service:
    # <<: *java-service means inherit all properties from anchor
    <<: *java-service
    profiles: [ "idp" ]
    working_dir: /workspace/npm-idp-service
    ports:
      - "8081:8080"

  workspace-manager:
    <<: *java-service
    profiles: [ "workspace" ]
    working_dir: /workspace/nm-workspace-manager
    ports:
      - "8082:8080"

  code-indexing:
    <<: *java-service
    profiles: [ "idp" ]
    working_dir: /workspace/npm-idp-service
    ports:
      - "8083:8080"

volumes:
  gradle-cache: