include:
  - infra.consul.yml
  - infra.kafka.yml
  - infra.postgres.yml
  - infra.qdrant.yml
  - infra.mongodb.yml

services:
  frontend:
    container_name: frontend
    profiles: [ "frontend", "dev" ]
    env_file:
      - .env
    build:
      context: ../..
      dockerfile: docker/dev/frontend.dev.Dockerfile
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}

    working_dir: /workspace/frontend

    volumes:
      - ../../frontend:/workspace/frontend
      - pnpm-store:/home/app/.pnpm

    command: sh -c "pnpm install && pnpm dev -- --host"

    ports:
      - "4321:4321"

    environment:
      NODE_ENV: development
      CI: "true"


  # anchor, x- means extension field so this service gets ignored by execution
  x-java-service: &java-service
    build:
      context: ../..
      dockerfile: ../dev/java-service.dev.Dockerfile
  #  environment:
   #   - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

    volumes:
      - ../..:/workspace
      - gradle-cache:/root/.gradle

  identity-provider:
    container_name: identity-provider
    # <<: *java-service means inherit all properties from anchor
    <<: *java-service
    profiles: [ "identity-provider", "dev" ]
    ports:
      - "8081:8080"
      - "5001:5005"
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      APP_SECURITY_ISSUER_URI: http://identity-provider:8080
    command: ./gradlew identity-provider:bootRun --continuous

  app-service:
    container_name: app-service
    <<: *java-service
    profiles: [ "app-service", "dev" ]
    ports:
      - "8082:8080"
      - "5002:5005"
    command: ./gradlew app-service:bootRun --continuous

  insights-service:
    container_name: insights-service
    <<: *java-service
    profiles: [ "insights-service", "dev" ]
    ports:
      - "8083:8080"
      - "5003:5005"
    command: ./gradlew insights-service:bootRun --continuous

  workers:
    container_name: workers
    <<: *java-service
    profiles: [ "workers", "dev" ]
    ports:
      - "8084:8080"
      - "5004:5005"
    command: ./gradlew workers:bootRun --continuous

  ai-layer:
    container_name: ai-layer
    <<: *java-service
    profiles: [ "ai-layer", "dev" ]
    ports:
      - "8085:8080"
      - "5005:5005"
    command: ./gradlew ai-layer:bootRun --continuous

  gateway:
    container_name: gateway
    <<: *java-service
    profiles: [ "gateway", "dev" ]
    ports:
      - "8086:8080"
      - "5006:5005"
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      IDP_ISSUER_URI: http://identity-provider:8080
    command: ./gradlew gateway:bootRun --continuous

volumes:
  gradle-cache:
  pnpm-store:
