services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mi_base_de_datos
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=tu@email.com
      - PGADMIN_DEFAULT_PASSWORD=tu_pass_admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data: