services:
  nm-postgres:
    image: postgres:16-alpine
    container_name: nm-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nm_postgres
    volumes:
      - nm-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d nm_postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=tu@email.com
      - PGADMIN_DEFAULT_PASSWORD=tu_pass_admin
    ports:
      - "5050:80"
    depends_on:
      nm-postgres:
        condition: service_healthy
    restart: always

volumes:
  nm-postgres-data:
