server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: nm-api-gateway
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: gateway
        prefer-ip-address: true
        health-check-path: /actuator/health
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: app-service
              uri: lb://app-service
              predicates:
                - Path=/hello
            - id: idp
              uri: lb://identity-provider
              predicates:
                - Path=/api/idp/**
              filters:
                - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDP_ISSUER_URI:http://localhost:8081}

app:
  idp:
    internal-uri: ${IDP_ISSUER_URI:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
