server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: nm-api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: idp
              uri: http://localhost:8081
              predicates:
                - Path=/api/idp/**
              filters:
                - StripPrefix=2
