server:
  port: 8081

spring:
  application:
    name: nm-idp-service
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
        provider:
          github:
            user-name-attribute: login

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
